### ISSUE TITLE
Japanese "Welcome" word "いらっしゃいませ" is not appropriate

### ISSUE THREAD

**Issue by manjuu-eater** [mdn/.github#21]
The word "いらっしゃいませ" is a greeting used by store clerks when a customer comes into the store.
I think this is not appropriate for welcome page of open-source repository...

Replaceable words:
1. "ようこそ"
2. "いらっしゃい"

The word 1. "ようこそ" means "welcome".
This word is known as [Windows XP login welcome message](https://www.google.com/search?q=%E3%82%88%E3%81%86%E3%81%93%E3%81%9D+windows&tbm=isch).
This word has a nuance of "thank you for coming".

e.g.) "ようこそ 日本へ" == "Welcome to Japan".

The word 2. "いらっしゃい" is kind of "welcome" or "come here".
This word is often used when guests or friends come to visit homes.
A little casual word than 1.
This word has a nuance of "please come here".

literally meaning of "いらっしゃい" is "please come here". It has also come to mean "welcome".
"いらっしゃい**ませ** (current word)" is polite and traditional version of "いらっしゃい". This is now used by only store clerks.

See also: https://ja.hinative.com/questions/4502418

**Comment by manjuu-eater** [comment]
Should I change the word with my own senses?
If so, I'll make a PR.

**Comment by WinstonSung** [comment]
I would suggest you just to create a new pull request about this issue.

**Comment by bsmth** [comment]
Fixed in https://github.com/mdn/.github/pull/22 🎉
